### ISSUE TITLE
打开网址后空白，但会下载首页

### ISSUE THREAD

**Issue by gukemanbu** [y500/YYDebugDatabase#17]
demo运行后，根据输出信息，在chrome里打开网址后，直接下载一个叫“下载”的无后辍文件，内容为首页html代码
运行环境:
mac：M1 11.6
xcode：13.2.1
模拟器：iOS15.2
chrome：98.0.4758.109（正式版本） (arm64)

**Comment by gukemanbu** [comment]
此问题已经解决，我提交了一个pull request，请有时间看下
[https://github.com/y500/iOSDebugDatabase/pull/18](url)

**Comment by y500** [comment]
感谢，已合并。
