### ISSUE TITLE
连接不稳定

### ISSUE THREAD

**Issue by lyuxxx** [y500/YYDebugDatabase#2]
偶尔能看到一两次数据,还需要设置什么?

**Comment by y500** [comment]
具体点儿，什么环境，什么浏览器？

**Comment by lyuxxx** [comment]
High Sierra 10.13.1
iOS 10.3.1
Chrome 63.0.3239.84

**Comment by y500** [comment]
试了一下chrome，会出现这种情况，感觉跟类似adblock这样的插件有关系，不太确定，可以用Firefox试试

**Comment by y500** [comment]
请使用最新版，把CocoaAsynSocket换成了GCDWebServer，彻底解决了这个问题
