### ISSUE TITLE
真机连接了chares，再输入地址Visit http://192.168.0.14:9002/ in your web browser，就报错了

### ISSUE THREAD

**Issue by changpk** [y500/YYDebugDatabase#3]
真机不连代理，是可以正常在浏览器里面调试数据库的，由于项目经常调试接口和查看数据库经常是同时进行的，所以一般都要链接charles。这个时候浏览器里面输入上述地址就不能访问了如下图所示
![1](https://user-images.githubusercontent.com/5789904/33972074-d38e7ffc-e0b6-11e7-9707-90308fc60320.png)
这种场景的问题是？

**Comment by y500** [comment]
这是跟网络路由有关，是正常情况，说来话长
