### ISSUE TITLE
关于集成代码

### ISSUE THREAD

**Issue by ripperhe** [y500/YYDebugDatabase#7]
大佬，我正在写一个用于 debug 的插件，开源的，非商用。我觉得你的这个点子很好，准备集成到里面去，应该会根据自己的需求修改一些代码。请问一下可以吗？我会 README 注明的

**Comment by y500** [comment]
可以的，注明作者和来源还有LICENSE就好

**Comment by ripperhe** [comment]
好的 👌  还有个问题想咨询一下，我看到源代码里面就是每次收到请求的时候，就打开数据库进行增删改查的操作，然后关闭返回结果。如果这个时候，客户端其他有代码也在操作这个数据库，是否就会造成数据错乱? 线程安全吗？
