### ISSUE TITLE
网页上查看表数据时crash

### ISSUE THREAD

**Issue by momoAI** [y500/YYDebugDatabase#8]
报错：Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (_NSInlineData)'
ps: 我们表的主键都是GUID类型 是类型转换问题吗

**Comment by y500** [comment]
把数据库文件发我邮箱 yanqizhou@126.com，我看一下

**Comment by y500** [comment]
感谢你的反馈，已添加guid类型的数据展示的支持。
